Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = "1024"
    v.cpus = 2
    v.customize ["modifyvm", :id, "--cpuexecutioncap", "70"]
  end
  config.vm.define "winELKAD01" do |winELKAD01|
    winELKAD01.vm.box = "https://app.vagrantup.com/mwrock/boxes/Windows2012R2"
    winELKAD01.vm.box = "mwrock/Windows2012R2"
    winELKAD01.vm.hostname = "winEOD01"
    winELKAD01.vm.network "private_network", ip: "192.168.60.170"
  end

  config.vm.define "mongodb01" do |mongodb|
    #mongodb.vm.box = "generic/rhel7"
#   mongodb.vm.box = "iamseth/rhel-7.3"
#   mongodb.vm.box = "oravirt/rhel75"
    #mongodb.vm.box = "javier-lopez/rhel-7.4"
    #mongodb.vm.box = "xianlin/rhel-7.4"
    mongodb.vm.box = "RH7.5_BaseRepo"
    mongodb.vm.hostname = "mongodb01"
    mongodb.vm.network "private_network", ip: "192.168.60.132"
    mongodb.vm.provision "shell", :inline => "sudo echo '192.168.60.132 mongodb01.local mongodb01' >> /etc/hosts"
         
    mongodb.vm.provision "ansible" do |ansible|
      ansible.playbook = "deploy_mongodb.yml"
      ansible.inventory_path = "vagrant_hosts"
      #ansible.tags = ansible_tags
      #ansible.verbose = ansible_verbosity
      #ansible.extra_vars = ansible_extra_vars
      #ansible.limit = ansible_limit
    end
  end
end
