- hosts: ancillaryRH7
  become: yes
  become_method: sudo
  roles:
    - umask
    - devtools
    - open_office
    - evince
    - stattransfer
    - sublime
    - ultra-edit
  post_tasks:
    - name: Install texlive
      yum:
        name: texlive
        state: present
