- hosts: ancillaryRH7
  become: yes
  become_method: sudo
  pre_tasks:
    - name: register RHEL7.5
      command: "/usr/bin/subscription-manager register --username <name> --password <password> --auto-attach"
  roles:
    - umask
    - devtools
    - open_office
    - evince
    - stattransfer
    - sublime
    - ultra-edit
  post_tasks:
    - name: remove RHEL7.5
      command:  "/usr/bin/subscription-manager remove --all"
    - name: unregister RHEL7.5
      command:  "/usr/bin/subscription-manager unregister"
    - name: clean RHEL7.5
      command:  "/usr/bin/subscription-manager clean"
    - name: Install texlive
      yum:
        name: texlive
        state: present
