Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = "1024"
    v.cpus = 2
    v.customize ["modifyvm", :id, "--cpuexecutioncap", "70"]
  end

  config.vm.define "ancillaryRH7" do |ancillaryRH7|
#   ancillaryRH7.vm.box = "generic/rhel7"
    ancillaryRH7.vm.box = "RH7.5_baserepo"
    #ancillaryRH7.vm.box = "javier-lopez/rhel-7.4"
    #ancillaryRH7.vm.box = "xianlin/rhel-7.4"
    ancillaryRH7.vm.hostname = "ancillaryRH7"
    ancillaryRH7.vm.network "private_network", ip: "192.168.60.189"
    ancillaryRH7.vm.provision "shell", :inline => "sudo echo '192.168.60.189 ancillaryRH7.local ancillaryRH7' >> /etc/hosts"
    ancillaryRH7.vm.provision "ansible" do |ansible|
      ansible.playbook = "deploy_ancillaryRH7.yml"
      ansible.inventory_path = "vagrant_hosts"
      #ansible.tags = ansible_tags
      #ansible.verbose = ansible_verbosity
      #ansible.extra_vars = ansible_extra_vars
      #ansible.limit = ansible_limit
    end
  end
end
